spring:
  application:
    name: spring-weather-service
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: weather
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS weather
      connection-timeout: 10000
openweather:
  api:
    weatherNow: https://api.openweathermap.org/data/2.5/weather?q=&lang=ru&units=metric&appid=
    weatherForecast: https://api.openweathermap.org/data/2.5/forecast?q=&lang=ru&units=metric&appid=
    key:

